/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Telas;

import DAO.AnimalDAO;
import DAO.ProducaoDiariaDAO;
import Model.Animal;
import Model.ProducaoDiaria;
import static java.lang.Double.parseDouble;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author 285146
 */
public class JFrame_ProducaoDiaria extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_ProducaoDiaria
     */
    public JFrame_ProducaoDiaria() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        try
        {
            MaskFormatter Data = new MaskFormatter("##/##/####");
            Data.setPlaceholderCharacter('_');
            jFormattedTextField_data.setFormatterFactory(new DefaultFormatterFactory(Data));
        }
        catch (ParseException exc)
        {}
        try
        {
            MaskFormatter QntLitros = new MaskFormatter("#.###");
            jFormattedTextField_quantidadeLitros.setFormatterFactory(new DefaultFormatterFactory(QntLitros));    
        }
        catch (ParseException exc)
        {}
        jTextField_nomeAnimal.disable();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_registrarProduçãoPorAnimal = new javax.swing.JLabel();
        jLabel_BrincotelaRegistrar = new javax.swing.JLabel();
        jTextField_numeroBrinco = new javax.swing.JTextField();
        jLabel_data = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField_data = new javax.swing.JFormattedTextField();
        jFormattedTextField_quantidadeLitros = new javax.swing.JFormattedTextField();
        jTextField_nomeAnimal = new javax.swing.JTextField();
        jButton_gravar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jLabel_Erro_Data = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_registrarProduçãoPorAnimal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_registrarProduçãoPorAnimal.setText("Registrar produção diária por animal");

        jLabel_BrincotelaRegistrar.setText("Brinco: *");

        jTextField_numeroBrinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numeroBrincoActionPerformed(evt);
            }
        });

        jLabel_data.setText("Data:*");

        jLabel4.setText("Quantidade litros:*");

        jFormattedTextField_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField_data.setText("dd/mm/yyyy");

        jFormattedTextField_quantidadeLitros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jButton_gravar.setText("Gravar");
        jButton_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gravarActionPerformed(evt);
            }
        });

        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });

        jLabel_Erro_Data.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Erro_Data.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField_quantidadeLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_BrincotelaRegistrar)
                            .addComponent(jLabel_data))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextField_data, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Erro_Data))
                            .addComponent(jTextField_numeroBrinco, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_nomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_registrarProduçãoPorAnimal)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_gravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_cancelar)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel_registrarProduçãoPorAnimal)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_BrincotelaRegistrar)
                    .addComponent(jTextField_numeroBrinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_data)
                    .addComponent(jFormattedTextField_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Erro_Data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField_quantidadeLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_gravar)
                    .addComponent(jButton_cancelar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_numeroBrincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numeroBrincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numeroBrincoActionPerformed

    private void jButton_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gravarActionPerformed
        ProducaoDiaria pd = new ProducaoDiaria();
        ArrayList<Animal> ListaAnimal = AnimalDAO.getListaAnimais();
        for(Animal a:ListaAnimal){
            if(a.getNumero().equals(jTextField_numeroBrinco.getText())) {
                pd.setIdAnimal(a.getId());
            }
        }
        try
        {
            java.util.Date dataUtil = new SimpleDateFormat("dd/MM/yyyy").parse(jFormattedTextField_data.getText());
            Date data = new Date(dataUtil.getTime());
            pd.setData(data);
        } catch (ParseException ex) {
            jLabel_Erro_Data.setText("Data inválida!");
            return;
        }
        pd.setQntLitros(parseDouble(jFormattedTextField_quantidadeLitros.getText()));
        ProducaoDiariaDAO.registrarProducao(pd);  
        jTextField_nomeAnimal.setText(null);
        jTextField_numeroBrinco.setText(null);
        jFormattedTextField_data.setText(null);
        jFormattedTextField_quantidadeLitros.setText(null);
        
    }//GEN-LAST:event_jButton_gravarActionPerformed

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_ProducaoDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_ProducaoDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_ProducaoDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_ProducaoDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_ProducaoDiaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_gravar;
    private javax.swing.JFormattedTextField jFormattedTextField_data;
    private javax.swing.JFormattedTextField jFormattedTextField_quantidadeLitros;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_BrincotelaRegistrar;
    private javax.swing.JLabel jLabel_Erro_Data;
    private javax.swing.JLabel jLabel_data;
    private javax.swing.JLabel jLabel_registrarProduçãoPorAnimal;
    private javax.swing.JTextField jTextField_nomeAnimal;
    private javax.swing.JTextField jTextField_numeroBrinco;
    // End of variables declaration//GEN-END:variables
}
